backend:
  name: git-gateway # Or github, gitlab, etc.
  branch: main # Or your default branch

media_folder: public/images
public_folder: /images

collections:
  - name: 'artwork'
    label: 'Artwork'
    folder: 'artwork'
    create: true
    fields:
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Publish Date', name: 'date', widget: 'datetime' }
      - { label: 'Image', name: 'image', widget: 'image' }
      - { label: 'Caption', name: 'caption', widget: 'string' }
      - { label: 'Description', name: 'body', widget: 'markdown' }